#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from src/parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "src/parser.y"

    #include <cstdio>
    #include <iostream>
    #include <sstream>
    #include <string>
    #include <cstring>
    #include "AllNodes.h"
    #include "MJJProgram.h"

    #define YYDEBUG 1

    extern "C" int yylex();
    extern "C" int yyparse();
    extern "C" FILE *yyin;

    using namespace std;

    void yyerror(const char *s);


#line 22 "src/parser.y"
typedef union{
    int ival;
    const char* sval;
    Node* nval;
    ClassNode* cnval;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	CLASS	258
#define	FINAL	259
#define	MAIN	260
#define	IF	261
#define	ELSE	262
#define	WHILE	263
#define	TRUE	264
#define	FALSE	265
#define	RETURN	266
#define	VOID	267
#define	INT	268
#define	BOOLEAN	269
#define	OTHER	270
#define	EQUAL	271
#define	PLUS_EQUAL	272
#define	INC	273
#define	NOT	274
#define	AND	275
#define	OR	276
#define	EQUAL_EQUAL	277
#define	GREATER	278
#define	PLUS	279
#define	MINUS	280
#define	TIMES	281
#define	DIV	282
#define	O_C_BRACE	283
#define	C_C_BRACE	284
#define	SEMICOLON	285
#define	O_S_BRACKET	286
#define	C_S_BRACKET	287
#define	O_BRACKET	288
#define	C_BRACKET	289
#define	COMMA	290
#define	IDENTIFIER	291
#define	NUMBER	292


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int CLASS;
static const int FINAL;
static const int MAIN;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int TRUE;
static const int FALSE;
static const int RETURN;
static const int VOID;
static const int INT;
static const int BOOLEAN;
static const int OTHER;
static const int EQUAL;
static const int PLUS_EQUAL;
static const int INC;
static const int NOT;
static const int AND;
static const int OR;
static const int EQUAL_EQUAL;
static const int GREATER;
static const int PLUS;
static const int MINUS;
static const int TIMES;
static const int DIV;
static const int O_C_BRACE;
static const int C_C_BRACE;
static const int SEMICOLON;
static const int O_S_BRACKET;
static const int C_S_BRACKET;
static const int O_BRACKET;
static const int C_BRACKET;
static const int COMMA;
static const int IDENTIFIER;
static const int NUMBER;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,CLASS=258
	,FINAL=259
	,MAIN=260
	,IF=261
	,ELSE=262
	,WHILE=263
	,TRUE=264
	,FALSE=265
	,RETURN=266
	,VOID=267
	,INT=268
	,BOOLEAN=269
	,OTHER=270
	,EQUAL=271
	,PLUS_EQUAL=272
	,INC=273
	,NOT=274
	,AND=275
	,OR=276
	,EQUAL_EQUAL=277
	,GREATER=278
	,PLUS=279
	,MINUS=280
	,TIMES=281
	,DIV=282
	,O_C_BRACE=283
	,C_C_BRACE=284
	,SEMICOLON=285
	,O_S_BRACKET=286
	,C_S_BRACKET=287
	,O_BRACKET=288
	,C_BRACKET=289
	,COMMA=290
	,IDENTIFIER=291
	,NUMBER=292


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::CLASS=258;
const int YY_parse_CLASS::FINAL=259;
const int YY_parse_CLASS::MAIN=260;
const int YY_parse_CLASS::IF=261;
const int YY_parse_CLASS::ELSE=262;
const int YY_parse_CLASS::WHILE=263;
const int YY_parse_CLASS::TRUE=264;
const int YY_parse_CLASS::FALSE=265;
const int YY_parse_CLASS::RETURN=266;
const int YY_parse_CLASS::VOID=267;
const int YY_parse_CLASS::INT=268;
const int YY_parse_CLASS::BOOLEAN=269;
const int YY_parse_CLASS::OTHER=270;
const int YY_parse_CLASS::EQUAL=271;
const int YY_parse_CLASS::PLUS_EQUAL=272;
const int YY_parse_CLASS::INC=273;
const int YY_parse_CLASS::NOT=274;
const int YY_parse_CLASS::AND=275;
const int YY_parse_CLASS::OR=276;
const int YY_parse_CLASS::EQUAL_EQUAL=277;
const int YY_parse_CLASS::GREATER=278;
const int YY_parse_CLASS::PLUS=279;
const int YY_parse_CLASS::MINUS=280;
const int YY_parse_CLASS::TIMES=281;
const int YY_parse_CLASS::DIV=282;
const int YY_parse_CLASS::O_C_BRACE=283;
const int YY_parse_CLASS::C_C_BRACE=284;
const int YY_parse_CLASS::SEMICOLON=285;
const int YY_parse_CLASS::O_S_BRACKET=286;
const int YY_parse_CLASS::C_S_BRACKET=287;
const int YY_parse_CLASS::O_BRACKET=288;
const int YY_parse_CLASS::C_BRACKET=289;
const int YY_parse_CLASS::COMMA=290;
const int YY_parse_CLASS::IDENTIFIER=291;
const int YY_parse_CLASS::NUMBER=292;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		126
#define	YYFLAG		-32768
#define	YYNTBASE	38

#define YYTRANSLATE(x) ((unsigned)(x) <= 292 ? yytranslate[x] : 61)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     9,    11,    15,    16,    18,    20,    24,    25,
    29,    35,    40,    43,    44,    54,    60,    64,    66,    67,
    70,    74,    75,    79,    83,    86,    91,    94,   104,   110,
   118,   122,   124,   125,   128,   132,   136,   138,   142,   146,
   148,   152,   156,   159,   161,   165,   169,   171,   173,   178,
   180,   182,   184,   188,   190,   195,   197,   199,   201
};

static const short yyrhs[] = {    39,
     0,     3,    40,    28,    41,    47,    29,     0,    36,     0,
    42,    30,    41,     0,     0,    44,     0,    46,     0,    44,
    30,    43,     0,     0,    59,    40,    45,     0,    59,    40,
    31,    53,    32,     0,     4,    60,    40,    45,     0,    16,
    53,     0,     0,    59,    40,    33,    48,    34,    28,    43,
    50,    29,     0,     5,    28,    43,    50,    29,     0,    49,
    35,    48,     0,    49,     0,     0,    60,    40,     0,    51,
    30,    50,     0,     0,    58,    16,    53,     0,    58,    17,
    53,     0,    58,    18,     0,    40,    33,    52,    34,     0,
    11,    53,     0,     6,    53,    28,    50,    29,     7,    28,
    50,    29,     0,     6,    53,    28,    50,    29,     0,     8,
    33,    53,    34,    28,    50,    29,     0,    53,    35,    52,
     0,    53,     0,     0,    19,    54,     0,    53,    20,    54,
     0,    53,    21,    54,     0,    54,     0,    54,    22,    55,
     0,    54,    23,    55,     0,    55,     0,    55,    24,    56,
     0,    55,    25,    56,     0,    25,    56,     0,    56,     0,
    56,    26,    57,     0,    56,    27,    57,     0,    57,     0,
    58,     0,    40,    33,    52,    34,     0,     9,     0,    10,
     0,    37,     0,    33,    53,    34,     0,    40,     0,    40,
    31,    53,    32,     0,    12,     0,    60,     0,    13,     0,
    14,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    43,    51,    59,    67,    72,    78,    80,    83,    88,    94,
    99,   103,   109,   111,   117,   124,   131,   136,   141,   147,
   154,   159,   165,   170,   174,   178,   182,   186,   190,   194,
   200,   205,   210,   216,   221,   225,   229,   232,   237,   241,
   244,   249,   253,   257,   260,   265,   269,   272,   274,   278,
   282,   286,   291,   293,   295,   301,   306,   309,   314
};

static const char * const yytname[] = {   "$","error","$illegal.","CLASS","FINAL",
"MAIN","IF","ELSE","WHILE","TRUE","FALSE","RETURN","VOID","INT","BOOLEAN","OTHER",
"EQUAL","PLUS_EQUAL","INC","NOT","AND","OR","EQUAL_EQUAL","GREATER","PLUS","MINUS",
"TIMES","DIV","O_C_BRACE","C_C_BRACE","SEMICOLON","O_S_BRACKET","C_S_BRACKET",
"O_BRACKET","C_BRACKET","COMMA","IDENTIFIER","NUMBER","start","classe","ident",
"decls","decl","vars","var","vexp","methode","methmain","entetes","entete","instrs",
"instr","listexp","exp","exp1","exp2","terme","fact","ident1","typemeth","type",
""
};
#endif

static const short yyr1[] = {     0,
    38,    39,    40,    41,    41,    42,    42,    43,    43,    44,
    44,    44,    45,    45,    46,    47,    48,    48,    48,    49,
    50,    50,    51,    51,    51,    51,    51,    51,    51,    51,
    52,    52,    52,    53,    53,    53,    53,    54,    54,    54,
    55,    55,    55,    55,    56,    56,    56,    57,    57,    57,
    57,    57,    57,    58,    58,    59,    59,    60,    60
};

static const short yyr2[] = {     0,
     1,     6,     1,     3,     0,     1,     1,     3,     0,     3,
     5,     4,     2,     0,     9,     5,     3,     1,     0,     2,
     3,     0,     3,     3,     2,     4,     2,     9,     5,     7,
     3,     1,     0,     2,     3,     3,     1,     3,     3,     1,
     3,     3,     2,     1,     3,     3,     1,     1,     4,     1,
     1,     1,     3,     1,     4,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
     0,     1,     3,     0,     5,     0,    56,    58,    59,     0,
     0,     6,     7,     0,    57,     0,     0,     0,     5,    14,
    14,     9,     2,     4,     0,     0,    19,    10,    12,    22,
     0,     0,    50,    51,     0,     0,     0,    52,    54,    13,
    37,    40,    44,    47,    48,     0,     0,    18,     0,     0,
     0,     0,    54,     0,     0,     0,     9,    14,    34,    43,
     0,     0,    33,     0,     0,     0,     0,     0,     0,     0,
     0,    11,     0,    19,    20,     0,     0,    27,    33,    16,
    22,     0,     0,    25,     8,    53,     0,     0,    32,    35,
    36,    38,    39,    41,    42,    45,    46,     9,    17,    22,
     0,     0,    21,    23,    24,    55,    49,    33,    22,     0,
     0,    26,    31,     0,    29,    22,    15,     0,     0,    22,
    30,     0,    28,     0,     0,     0
};

static const short yydefgoto[] = {   124,
     2,    39,    10,    11,    30,    31,    28,    13,    18,    47,
    48,    54,    55,    88,    89,    41,    42,    43,    44,    45,
    32,    15
};

static const short yypact[] = {    16,
    38,-32768,-32768,    17,   108,    96,-32768,-32768,-32768,    56,
    54,-32768,-32768,    38,-32768,    38,    59,    66,   108,     4,
    75,   108,-32768,-32768,    40,    40,    96,-32768,-32768,    10,
    70,    38,-32768,-32768,    42,    61,    40,-32768,    27,     3,
    94,    99,   100,-32768,-32768,    69,    73,    76,    38,    40,
    80,    40,    33,    89,    95,    88,   108,    25,    94,   100,
    34,    40,    40,    42,    42,    42,    42,    61,    61,    61,
    61,-32768,   103,    96,-32768,    65,    40,     3,    40,-32768,
    10,    40,    40,-32768,-32768,-32768,    82,    98,   -10,    94,
    94,    99,    99,   100,   100,-32768,-32768,   108,-32768,    10,
    62,   102,-32768,     3,     3,-32768,-32768,    40,    10,   104,
   109,-32768,-32768,   110,   121,    10,-32768,   112,   113,    10,
-32768,   114,-32768,   138,   141,-32768
};

static const short yypgoto[] = {-32768,
-32768,    -1,   125,-32768,   -54,     7,   124,-32768,-32768,    72,
-32768,   -73,-32768,   -70,   -20,   -31,    63,   -29,    64,   -28,
     9,    -5
};


#define	YYLAST		146


static const short yytable[] = {     4,
    16,    56,    85,    59,    40,    46,    60,   103,   102,    64,
    65,    12,    20,    14,    21,    50,    61,    51,     1,    25,
    52,    49,    64,    65,   108,    12,   110,    14,    53,    76,
    58,    78,    90,    91,    26,   114,    27,   113,    94,    95,
    25,    87,   119,   109,     5,     3,   122,    75,    33,    34,
    33,    34,    56,    64,    65,    26,   101,    62,    35,    63,
    17,   104,   105,    62,    36,    79,    36,    86,    49,    33,
    34,    56,    37,     3,    37,     3,    38,     3,    38,    53,
    56,    64,    65,    19,    64,    65,    22,    56,    64,    65,
    25,    56,   100,    37,    23,   111,     3,    38,    53,    57,
    72,    64,    65,    82,    83,    84,    73,    53,     8,     9,
    74,     6,    77,   106,    53,    66,    67,    80,    53,     7,
     8,     9,    68,    69,    81,    70,    71,   118,    92,    93,
    98,   107,   115,    96,    97,   112,   116,   125,   117,   120,
   126,   121,   123,    24,    29,    99
};

static const short yycheck[] = {     1,
     6,    30,    57,    35,    25,    26,    36,    81,    79,    20,
    21,     5,    14,     5,    16,     6,    37,     8,     3,    16,
    11,    27,    20,    21,    35,    19,   100,    19,    30,    50,
    32,    52,    64,    65,    31,   109,    33,   108,    68,    69,
    16,    62,   116,    98,    28,    36,   120,    49,     9,    10,
     9,    10,    81,    20,    21,    31,    77,    31,    19,    33,
     5,    82,    83,    31,    25,    33,    25,    34,    74,     9,
    10,   100,    33,    36,    33,    36,    37,    36,    37,    81,
   109,    20,    21,    30,    20,    21,    28,   116,    20,    21,
    16,   120,    28,    33,    29,    34,    36,    37,   100,    30,
    32,    20,    21,    16,    17,    18,    34,   109,    13,    14,
    35,     4,    33,    32,   116,    22,    23,    29,   120,    12,
    13,    14,    24,    25,    30,    26,    27,     7,    66,    67,
    28,    34,    29,    70,    71,    34,    28,     0,    29,    28,
     0,    29,    29,    19,    21,    74
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 44 "src/parser.y"
{
                cout << "Génération de l'arbre de syntaxe abstraite terminée." << endl;
                cout << "Appel à la fonction de callback..." << endl;
                MJJProgram::onAbstractSyntaxTreeCompleted(yyvsp[0].cnval);
        ;
    break;}
case 2:
#line 52 "src/parser.y"
{
            cout << "Génération de l'arbre de syntaxe abstraite..." << endl;
            ClassNode* cn = new ClassNode(yyvsp[-4].nval, yyvsp[-2].nval, yyvsp[-1].nval);
            yyval.cnval = cn;
        ;
    break;}
case 3:
#line 60 "src/parser.y"
{
            LeafNode* ln = new LeafNode(yyvsp[0].sval);
            IdentNode* in = new IdentNode(ln);
            yyval.nval = in;
        ;
    break;}
case 4:
#line 68 "src/parser.y"
{
            DeclsNode* dsn = new DeclsNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = dsn;
        ;
    break;}
case 5:
#line 72 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 6:
#line 79 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 7:
#line 80 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 8:
#line 84 "src/parser.y"
{
            VarsNode* vsn = new VarsNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = vsn;
        ;
    break;}
case 9:
#line 88 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 10:
#line 95 "src/parser.y"
{
            VarNode* vn = new VarNode(yyvsp[-2].nval, yyvsp[-1].nval, yyvsp[0].nval);
            yyval.nval = vn;
        ;
    break;}
case 11:
#line 99 "src/parser.y"
{
            TernaryArrayNode* tan = new TernaryArrayNode(yyvsp[-4].nval, yyvsp[-3].nval, yyvsp[-1].nval);
            yyval.nval = tan;
        ;
    break;}
case 12:
#line 103 "src/parser.y"
{
            CstNode* cstn = new CstNode(yyvsp[-2].nval, yyvsp[-1].nval, yyvsp[0].nval);
            yyval.nval = cstn;
        ;
    break;}
case 13:
#line 110 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 14:
#line 111 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 15:
#line 118 "src/parser.y"
{
            MethodNode* mdn = new MethodNode(yyvsp[-8].nval, yyvsp[-7].nval, yyvsp[-5].nval, yyvsp[-2].nval, yyvsp[-1].nval);
            yyval.nval = mdn;
        ;
    break;}
case 16:
#line 125 "src/parser.y"
{
            MainNode* mn = new MainNode(yyvsp[-2].nval, yyvsp[-1].nval);
            yyval.nval = mn;
        ;
    break;}
case 17:
#line 132 "src/parser.y"
{
            HeadersNode* hsn = new HeadersNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = hsn;
        ;
    break;}
case 18:
#line 136 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            HeadersNode* hsn = new HeadersNode(yyvsp[0].nval, ln);
            yyval.nval = hsn;
        ;
    break;}
case 19:
#line 141 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 20:
#line 148 "src/parser.y"
{
            HeaderNode* hn = new HeaderNode(yyvsp[-1].nval, yyvsp[0].nval);
            yyval.nval = hn;
        ;
    break;}
case 21:
#line 155 "src/parser.y"
{
            InstrsNode* insn = new InstrsNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = insn;
        ;
    break;}
case 22:
#line 159 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 23:
#line 166 "src/parser.y"
{
            AssignmentNode* an = new AssignmentNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = an;
        ;
    break;}
case 24:
#line 170 "src/parser.y"
{
            SumNode* sn = new SumNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = sn;
        ;
    break;}
case 25:
#line 174 "src/parser.y"
{
            IncrementNode* incn = new IncrementNode(yyvsp[-1].nval);
            yyval.nval = incn;
        ;
    break;}
case 26:
#line 178 "src/parser.y"
{
            CallINode* cin = new CallINode(yyvsp[-3].nval, yyvsp[-1].nval);
            yyval.nval = cin;
        ;
    break;}
case 27:
#line 182 "src/parser.y"
{
            ReturnNode* rn = new ReturnNode(yyvsp[0].nval);
            yyval.nval = rn;
        ;
    break;}
case 28:
#line 186 "src/parser.y"
{
            IfElseNode* ifn = new IfElseNode(yyvsp[-7].nval, yyvsp[-5].nval, yyvsp[-1].nval);
            yyval.nval = ifn;
        ;
    break;}
case 29:
#line 190 "src/parser.y"
{
            IfNode* ifn = new IfNode(yyvsp[-3].nval, yyvsp[-1].nval);
            yyval.nval = ifn;
        ;
    break;}
case 30:
#line 194 "src/parser.y"
{
            WhileNode* wn = new WhileNode(yyvsp[-4].nval, yyvsp[-1].nval);
            yyval.nval = wn;
        ;
    break;}
case 31:
#line 201 "src/parser.y"
{
            ExpListNode* eln = new ExpListNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = eln;
        ;
    break;}
case 32:
#line 205 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            ExpListNode* eln = new ExpListNode(yyvsp[0].nval, ln);
            yyval.nval = eln;
        ;
    break;}
case 33:
#line 210 "src/parser.y"
{
            LeafNode* ln = new LeafNode("");
            yyval.nval = ln;
        ;
    break;}
case 34:
#line 217 "src/parser.y"
{
            NotNode* nn = new NotNode(yyvsp[0].nval);
            yyval.nval = nn;
        ;
    break;}
case 35:
#line 221 "src/parser.y"
{
            AndNode* andn = new AndNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = andn;
        ;
    break;}
case 36:
#line 225 "src/parser.y"
{
            OrNode* on = new OrNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = on;
        ;
    break;}
case 37:
#line 229 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 38:
#line 233 "src/parser.y"
{
            EqualityNode* en = new EqualityNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = en;
        ;
    break;}
case 39:
#line 237 "src/parser.y"
{
            GreaterThanNode* gtn = new GreaterThanNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = gtn;
        ;
    break;}
case 40:
#line 241 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 41:
#line 245 "src/parser.y"
{
            PlusNode* pn = new PlusNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = pn;
        ;
    break;}
case 42:
#line 249 "src/parser.y"
{
            BinaryMinusNode* bmn = new BinaryMinusNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = bmn;
        ;
    break;}
case 43:
#line 253 "src/parser.y"
{
            UnaryMinusNode* umn = new UnaryMinusNode(yyvsp[0].nval);
            yyval.nval = umn;
        ;
    break;}
case 44:
#line 257 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 45:
#line 261 "src/parser.y"
{
            TimesNode* tn = new TimesNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = tn;
        ;
    break;}
case 46:
#line 265 "src/parser.y"
{
            DivideNode* dn = new DivideNode(yyvsp[-2].nval, yyvsp[0].nval);
            yyval.nval = dn;
        ;
    break;}
case 47:
#line 269 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 48:
#line 273 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 49:
#line 274 "src/parser.y"
{
            CallENode* cen = new CallENode(yyvsp[-3].nval, yyvsp[-1].nval);
            yyval.nval = cen;
        ;
    break;}
case 50:
#line 278 "src/parser.y"
{
            LeafNode* ln = new LeafNode("true");
            yyval.nval = ln;
        ;
    break;}
case 51:
#line 282 "src/parser.y"
{
            LeafNode* ln = new LeafNode("false");
            yyval.nval = ln;
        ;
    break;}
case 52:
#line 286 "src/parser.y"
{
            LeafNode* ln = new LeafNode(yyvsp[0].sval);
            NumberNode* nn = new NumberNode(ln);
            yyval.nval = nn;
        ;
    break;}
case 53:
#line 291 "src/parser.y"
{yyval.nval = yyvsp[-1].nval;;
    break;}
case 54:
#line 294 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 55:
#line 295 "src/parser.y"
{
            BinaryArrayNode* ban = new BinaryArrayNode(yyvsp[-3].nval, yyvsp[-1].nval);
            yyval.nval = ban;
        ;
    break;}
case 56:
#line 302 "src/parser.y"
{
            LeafNode* ln = new LeafNode("void");
            yyval.nval = ln;
        ;
    break;}
case 57:
#line 306 "src/parser.y"
{yyval.nval = yyvsp[0].nval;;
    break;}
case 58:
#line 310 "src/parser.y"
{
            LeafNode* ln = new LeafNode("int");
            yyval.nval = ln;
        ;
    break;}
case 59:
#line 314 "src/parser.y"
{
            LeafNode* ln = new LeafNode("boolean");
            yyval.nval = ln;
        ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 320 "src/parser.y"

